const contactsDefault = [
  {
    id: 1,
    name: "David Evans",
    nickname: "Dave",
    email: "david@evans.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "2345678904",
    },
    workInfo: {
      jobTitle: "Software Tester",
      department: "QA",
      company: "TestCo",
    },
    address: {
      street: "2929 Birch St",
      city: "Summit",
      state: "USA",
      zip: "70770",
    },
    group: "friends",
    createdAt: "2022-09-18",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 2,
    name: "Grace Harris",
    nickname: "Gracie",
    email: "grace@harris.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "5678901237",
    },
    workInfo: {
      jobTitle: "Marketing Coordinator",
      department: "Marketing",
      company: "MarketCo",
    },
    address: {
      street: "3232 Willow St",
      city: "Ridge",
      state: "USA",
      zip: "10111",
    },
    group: "friends",
    createdAt: "2021-07-10",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 3,
    name: "Oscar Perez",
    nickname: "Ozzy",
    email: "oscar@perez.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "7890123457",
    },
    workInfo: {
      jobTitle: "Accountant",
      department: "Finance",
      company: "Money Matters",
    },
    address: {
      street: "1414 Dogwood St",
      city: "Lakeside",
      state: "USA",
      zip: "10101",
    },
    group: "friends",
    createdAt: "2023-03-28",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 4,
    name: "Henry Irving",
    nickname: "Hank",
    email: "henry@irving.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "6789012348",
    },
    workInfo: {
      jobTitle: "Operations Specialist",
      department: "Operations",
      company: "OpsCo",
    },
    address: {
      street: "3333 Aspen St",
      city: "Plateau",
      state: "USA",
      zip: "20221",
    },
    group: "work",
    createdAt: "2020-11-29",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 5,
    name: "Ian Jackson",
    nickname: "IJ",
    email: "ian@jackson.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "1234567891",
    },
    workInfo: {
      jobTitle: "Financial Analyst",
      department: "Finance",
      company: "Finance Pro",
    },
    address: {
      street: "808 Willow St",
      city: "Uptown",
      state: "USA",
      zip: "44545",
    },
    group: "friends",
    createdAt: "2017-06-14",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 6,
    name: "John Doe",
    nickname: "Johnny",
    email: "",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "1234567890",
    },
    workInfo: {
      jobTitle: "Software Engineer",
      department: "Engineering",
      company: "Acme Inc.",
    },
    address: {
      street: "123 Main St",
      city: "Anytown",
      state: "USA",
      zip: "12345",
    },
    group: "",
    createdAt: "2021-08-15",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 7,
    name: "Kevin Lewis",
    nickname: "Kev",
    email: "kevin@lewis.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "3456789013",
    },
    workInfo: {
      jobTitle: "IT Specialist",
      department: "IT",
      company: "Tech Support",
    },
    address: {
      street: "1010 Poplar St",
      city: "Suburbia",
      state: "USA",
      zip: "66767",
    },
    group: "",
    createdAt: "2019-01-19",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 8,
    name: "Michael Nelson",
    nickname: "Mike",
    email: "michael@nelson.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "5678901235",
    },
    workInfo: {
      jobTitle: "Business Analyst",
      department: "Business",
      company: "Biz Solutions",
    },
    address: {
      street: "1212 Palm St",
      city: "Capital City",
      state: "USA",
      zip: "88989",
    },
    group: "work",
    createdAt: "2021-09-21",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 9,
    name: "Nina Owens",
    nickname: "Nini",
    email: "nina@owens.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "6789012346",
    },
    workInfo: {
      jobTitle: "Recruiter",
      department: "HR",
      company: "Hire Me",
    },
    address: {
      street: "1313 Magnolia St",
      city: "Seaside",
      state: "USA",
      zip: "99090",
    },
    group: "",
    createdAt: "2022-12-15",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 10,
    name: "Paula Quinn",
    nickname: "PQ",
    email: "paula@quinn.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "8901234568",
    },
    workInfo: {
      jobTitle: "Legal Advisor",
      department: "Legal",
      company: "Law Firm",
    },
    address: {
      street: "1515 Cherry St",
      city: "Riverside",
      state: "USA",
      zip: "20202",
    },
    group: "work",
    createdAt: "2022-07-11",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 11,
    name: "Quincy Roberts",
    nickname: "Q",
    email: "quincy@roberts.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "9012345679",
    },
    workInfo: {
      jobTitle: "Research Scientist",
      department: "Research",
      company: "Lab Co.",
    },
    address: {
      street: "1616 Walnut St",
      city: "Hilltop",
      state: "USA",
      zip: "30303",
    },
    group: "",
    createdAt: "2021-11-30",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 12,
    name: "Rachel Scott",
    nickname: "Rach",
    email: "rachel@scott.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "0123456780",
    },
    workInfo: {
      jobTitle: "Event Planner",
      department: "Events",
      company: "Eventful",
    },
    address: {
      street: "1717 Maple St",
      city: "Valley",
      state: "USA",
      zip: "40404",
    },
    group: "friends",
    createdAt: "2020-02-17",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 13,
    name: "Sam Taylor",
    nickname: "Sammy",
    email: "sam@taylor.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "1234567892",
    },
    workInfo: {
      jobTitle: "Logistics Coordinator",
      department: "Logistics",
      company: "LogiCo",
    },
    address: {
      street: "1818 Pine St",
      city: "Mountain",
      state: "USA",
      zip: "50505",
    },
    group: "work",
    createdAt: "2019-06-25",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 14,
    name: "Tina Underwood",
    nickname: "T",
    email: "tina@underwood.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "2345678903",
    },
    workInfo: {
      jobTitle: "Public Relations",
      department: "PR",
      company: "PR Pros",
    },
    address: {
      street: "1919 Birch St",
      city: "Forest",
      state: "USA",
      zip: "60606",
    },
    group: "",
    createdAt: "2018-10-09",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 15,
    name: "Ursula Vance",
    nickname: "Urs",
    email: "ursula@vance.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "3456789014",
    },
    workInfo: {
      jobTitle: "Quality Assurance",
      department: "QA",
      company: "Quality Check",
    },
    address: {
      street: "2020 Cedar St",
      city: "Desert",
      state: "USA",
      zip: "70707",
    },
    group: "friends",
    createdAt: "2017-01-03",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 16,
    name: "Victor White",
    nickname: "Vic",
    email: "victor@white.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "4567890125",
    },
    workInfo: {
      jobTitle: "Security Specialist",
      department: "Security",
      company: "Secure It",
    },
    address: {
      street: "2121 Redwood St",
      city: "Oasis",
      state: "USA",
      zip: "80808",
    },
    group: "work",
    createdAt: "2024-11-27",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 17,
    name: "Wendy Xander",
    nickname: "Wen",
    email: "wendy@xander.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "5678901236",
    },
    workInfo: {
      jobTitle: "Supply Chain Manager",
      department: "Supply Chain",
      company: "Supply Co.",
    },
    address: {
      street: "2222 Willow St",
      city: "Harbor",
      state: "USA",
      zip: "90909",
    },
    group: "",
    createdAt: "2024-09-14",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 18,
    name: "Xander Young",
    nickname: "Xan",
    email: "xander@young.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "6789012347",
    },
    workInfo: {
      jobTitle: "Technical Writer",
      department: "Documentation",
      company: "DocuWrite",
    },
    address: {
      street: "2323 Aspen St",
      city: "Bay",
      state: "USA",
      zip: "10110",
    },
    group: "friends",
    createdAt: "2016-12-01",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 19,
    name: "Yvonne Zane",
    nickname: "Yve",
    email: "yvonne@zane.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "7890123458",
    },
    workInfo: {
      jobTitle: "Product Owner",
      department: "Product",
      company: "ProdCo",
    },
    address: {
      street: "2424 Poplar St",
      city: "Cove",
      state: "USA",
      zip: "20220",
    },
    group: "work",
    createdAt: "2017-03-19",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 20,
    name: "Zachary Adams",
    nickname: "Zach",
    email: "zachary@adams.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "8901234569",
    },
    workInfo: {
      jobTitle: "Network Engineer",
      department: "IT",
      company: "NetCo",
    },
    address: {
      street: "2525 Cypress St",
      city: "Shore",
      state: "USA",
      zip: "30330",
    },
    group: "",
    createdAt: "2018-07-04",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 21,
    name: "Ava Baker",
    nickname: "Avie",
    email: "ava@baker.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "9012345670",
    },
    workInfo: {
      jobTitle: "Social Media Manager",
      department: "Marketing",
      company: "Socialize",
    },
    address: {
      street: "2626 Cherry St",
      city: "Cliff",
      state: "USA",
      zip: "40440",
    },
    group: "friends",
    createdAt: "2019-11-27",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 22,
    name: "Ben Carter",
    nickname: "Benny",
    email: "ben@carter.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "0123456781",
    },
    workInfo: {
      jobTitle: "DevOps Engineer",
      department: "Engineering",
      company: "DevOps Co.",
    },
    address: {
      street: "2727 Maple St",
      city: "Hill",
      state: "USA",
      zip: "50550",
    },
    group: "work",
    createdAt: "2020-02-14",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 23,
    name: "Chloe Davis",
    nickname: "Chlo",
    email: "chloe@davis.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "1234567893",
    },
    workInfo: {
      jobTitle: "HR Specialist",
      department: "HR",
      company: "HR Solutions",
    },
    address: {
      street: "2828 Pine St",
      city: "Peak",
      state: "USA",
      zip: "60660",
    },
    group: "",
    createdAt: "2021-06-01",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 24,
    name: "Diana Evans",
    nickname: "Di",
    email: "diana@evans.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "6789012345",
    },
    workInfo: {
      jobTitle: "HR Manager",
      department: "Human Resources",
      company: "People First",
    },
    address: {
      street: "303 Birch St",
      city: "Oldtown",
      state: "USA",
      zip: "77889",
    },
    group: "work",
    createdAt: "2018-12-20",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 25,
    name: "Ella Foster",
    nickname: "Ellie",
    email: "ella@foster.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "3456789015",
    },
    workInfo: {
      jobTitle: "Business Development",
      department: "Business",
      company: "BizDev",
    },
    address: {
      street: "3030 Cedar St",
      city: "Crest",
      state: "USA",
      zip: "80880",
    },
    group: "work",
    createdAt: "2023-12-05",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 26,
    name: "Frank Green",
    nickname: "Frankie",
    email: "frank@green.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "4567890126",
    },
    workInfo: {
      jobTitle: "Systems Administrator",
      department: "IT",
      company: "SysAdmin Co.",
    },
    address: {
      street: "3131 Redwood St",
      city: "Bluff",
      state: "USA",
      zip: "90990",
    },
    group: "",
    createdAt: "2022-03-22",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 27,
    name: "George Harris",
    nickname: "Geo",
    email: "george@harris.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "9012345678",
    },
    workInfo: {
      jobTitle: "Project Manager",
      department: "Projects",
      company: "Manage It",
    },
    address: {
      street: "606 Fir St",
      city: "Largetown",
      state: "USA",
      zip: "22323",
    },
    group: "work",
    createdAt: "2015-11-11",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 28,
    name: "Hannah Irving",
    nickname: "Han",
    email: "hannah@irving.com",
    name: "Henry Irving",
    nickname: "Hank",
    email: "henry@irving.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "6789012348",
    },
    workInfo: {
      jobTitle: "Operations Specialist",
      department: "Operations",
      company: "OpsCo",
    },
    address: {
      street: "3333 Aspen St",
      city: "Plateau",
      state: "USA",
      zip: "20221",
    },
    group: "work",
    createdAt: "2020-11-29",
    modifiedAt: "",
    isFavorited: false,
  },
  {
    id: 29,
    name: "Isla Jackson",
    nickname: "Izzy",
    email: "isla@jackson.com",
    phone: {
      countryCode: "+62",
      areaCode: "",
      phoneNumber: "7890123459",
    },
    workInfo: {
      jobTitle: "Financial Planner",
      department: "Finance",
      company: "FinanceCo",
    },
    address: {},
    group: "family",
    createdAt: "2019-02-16",
    modifiedAt: "",
    isFavorited: false,
  },
];
